apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: deny-all
  namespace: {{ .Values.namespace }}
spec: {}
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-transaction-api
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: transaction-api
  action: ALLOW
  rules:
    - to:
        - operation:
            methods: ["GET", "POST"]
            paths: ["/api/*", "/health"]