cloudflare:
  account: ""
  tunnelName: "aks-chizer-tunnel"
  tunnelId: "<your-tunnel-id>"
  secret: ""
  secretName: cloudflare-tunnel-token
  enableWarp: false
  ingress:
    - hostname: chizer.dev.nationsbenefits.com
      service: http://istio-ingressgateway.istio-ingress.svc.cluster.local:80
    - service: http_status:404

image:
  repository: cloudflare/cloudflared
  pullPolicy: IfNotPresent
  tag: ""

replicaCount: 2

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65532

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - cloudflared
        topologyKey: kubernetes.io/hostname